steps:
- name: 'gcr.io/cloud-builders/docker/train'
  args: ['build', '-t', 'gcr.io/braided-destiny-374308/tweet_classification', '.']
- name: 'gcr.io/cloud-builders/docker/train'
  args: ['push', 'gcr.io/braided-destiny-374308/tweet_classification']
