steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'train.dockerfile', '.', '-t', 'gcr.io/braided-destiny-374308/tweet_classification/train']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/braided-destiny-374308/tweet_classification/train']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'test.dockerfile', '.', '-t', 'gcr.io/braided-destiny-374308/tweet_classification/inference']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/braided-destiny-374308/tweet_classification/inference']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'app.dockerfile', '.', '-t', 'gcr.io/braided-destiny-374308/tweet_classification/api']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/braided-destiny-374308/tweet_classification/api']