workerPoolSpecs:
   machineSpec:
      machineType: n1-standard-8
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/braided-destiny-374308/tweet_classification